import type { ChatCompletionPreset } from './types.js'

export const DEFAULT_PRESET: ChatCompletionPreset = {
  name: 'Default',
  unlockedContextSize: false,
  contextSize: 8192,
  maxResponseLength: 1200,
  swipesPerGeneration: 1,
  streaming: true,
  temperature: 0.8,
  frequencyPenalty: 0,
  presencePenalty: 0,
  topP: 1,
  seed: -1,
  utilityPrompts: ['Write {{{char}}}\'s} next reply in a fictional chat between {{{char}}} and {{{user}}}. Write 1 reply only in internet RP style. Use markdown. Be proactive.'],
  continuePostfix: ' ',
  continuePrefill: false,
  characterNamesBehavior: 'default',
  squashSystemMessages: false,
  enableFunctionCalling: false,
  interleavedThinking: false,
  sendInlineMedia: false,
  inlineImageQuality: 'medium',
  requestModelReasoning: false,
  reasoningEffort: 'auto',
  verbosity: 'medium',
  logitBias: {},
}
