import { type } from 'arktype';

export const LoreGlobalData = type({
  personaDescription: 'string',
  characterDescription: 'string',
  characterPersonality: 'string',
  characterDepthPrompt: 'string',
  scenario: 'string',
  creatorNotes: 'string',
  trigger: 'string',
});

export const LoreConfig = type({
  depth: 'number.integer >= 0',
  caseSensitive: 'boolean',
  matchWholeWords: 'boolean',
  scanDepth: 'number.integer >= 0',
});

export const LoreEntry = type({
  uid: 'number.integer',
  'world?': 'string',
  key: 'string[]',
  keysecondary: 'string[]',
  comment: 'string',
  content: 'string',
  constant: 'boolean',
  selective: 'boolean',
  order: 'number',
  position: 'number.integer',
  disable: 'boolean',
  excludeRecursion: 'boolean',
  preventRecursion: 'boolean',
  delayUntilRecursion: 'boolean',
  depth: 'number',
  selectiveLogic: 'number.integer',
  group: 'string',
  groupOverride: 'boolean',
  groupWeight: 'number',
  probability: 'number',
  useProbability: 'boolean',
  'scanDepth?': 'number | null',
  'caseSensitive?': 'boolean | null',
  'matchWholeWords?': 'boolean | null',
  'useGroupScoring?': 'boolean | null',
  automationId: 'string',
  role: 'number',
  vectorized: 'boolean',
  'sticky?': 'number | null',
  'cooldown?': 'number | null',
  'delay?': 'number | null',
  matchPersonaDescription: 'boolean',
  matchCharacterDescription: 'boolean',
  matchCharacterPersonality: 'boolean',
  matchCharacterDepthPrompt: 'boolean',
  matchScenario: 'boolean',
  matchCreatorNotes: 'boolean',
  triggers: 'string[]',
  ignoreBudget: 'boolean',
  'hash?': 'number',
  'decorators?': 'string[]',
});

export const LoreScanResult = type({
  beforeEntries: 'string[]',
  afterEntries: 'string[]',
  emEntries: 'string[]',
  depthEntries: 'string[]',
  anBeforeEntries: 'string[]',
  anAfterEntries: 'string[]',
  outletEntries: 'string[]',
  allActivatedEntries: 'number[]',
});
