/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as LorebooksIndexRouteImport } from './routes/lorebooks/index'
import { Route as ChatsIndexRouteImport } from './routes/chats/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as LorebooksNewRouteImport } from './routes/lorebooks/new'
import { Route as LorebooksIdRouteImport } from './routes/lorebooks/$id'
import { Route as ChatsNewRouteImport } from './routes/chats/new'
import { Route as ChatsIdRouteImport } from './routes/chats/$id'
import { Route as CharactersNewRouteImport } from './routes/characters/new'
import { Route as CharactersIdRouteImport } from './routes/characters/$id'
import { Route as ApiChatGenerateRouteImport } from './routes/api/chat-generate'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as CharactersIdEditRouteImport } from './routes/characters/$id_.edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCharactersIdAvatarRouteImport } from './routes/api/characters/$id/avatar'
import { Route as ApiBackgroundsIdImageRouteImport } from './routes/api/backgrounds/$id/image'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const LorebooksIndexRoute = LorebooksIndexRouteImport.update({
  id: '/lorebooks/',
  path: '/lorebooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const LorebooksNewRoute = LorebooksNewRouteImport.update({
  id: '/lorebooks/new',
  path: '/lorebooks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LorebooksIdRoute = LorebooksIdRouteImport.update({
  id: '/lorebooks/$id',
  path: '/lorebooks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsNewRoute = ChatsNewRouteImport.update({
  id: '/chats/new',
  path: '/chats/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIdRoute = ChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersNewRoute = CharactersNewRouteImport.update({
  id: '/characters/new',
  path: '/characters/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatGenerateRoute = ApiChatGenerateRouteImport.update({
  id: '/api/chat-generate',
  path: '/api/chat-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdEditRoute = CharactersIdEditRouteImport.update({
  id: '/characters/$id_/edit',
  path: '/characters/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCharactersIdAvatarRoute = ApiCharactersIdAvatarRouteImport.update({
  id: '/api/characters/$id/avatar',
  path: '/api/characters/$id/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackgroundsIdImageRoute = ApiBackgroundsIdImageRouteImport.update({
  id: '/api/backgrounds/$id/image',
  path: '/api/backgrounds/$id/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat-generate': typeof ApiChatGenerateRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/new': typeof CharactersNewRoute
  '/chats/$id': typeof ChatsIdRoute
  '/chats/new': typeof ChatsNewRoute
  '/lorebooks/$id': typeof LorebooksIdRoute
  '/lorebooks/new': typeof LorebooksNewRoute
  '/characters/': typeof CharactersIndexRoute
  '/chats/': typeof ChatsIndexRoute
  '/lorebooks/': typeof LorebooksIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/characters/$id/edit': typeof CharactersIdEditRoute
  '/api/backgrounds/$id/image': typeof ApiBackgroundsIdImageRoute
  '/api/characters/$id/avatar': typeof ApiCharactersIdAvatarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat-generate': typeof ApiChatGenerateRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/new': typeof CharactersNewRoute
  '/chats/$id': typeof ChatsIdRoute
  '/chats/new': typeof ChatsNewRoute
  '/lorebooks/$id': typeof LorebooksIdRoute
  '/lorebooks/new': typeof LorebooksNewRoute
  '/characters': typeof CharactersIndexRoute
  '/chats': typeof ChatsIndexRoute
  '/lorebooks': typeof LorebooksIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/characters/$id/edit': typeof CharactersIdEditRoute
  '/api/backgrounds/$id/image': typeof ApiBackgroundsIdImageRoute
  '/api/characters/$id/avatar': typeof ApiCharactersIdAvatarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat-generate': typeof ApiChatGenerateRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/new': typeof CharactersNewRoute
  '/chats/$id': typeof ChatsIdRoute
  '/chats/new': typeof ChatsNewRoute
  '/lorebooks/$id': typeof LorebooksIdRoute
  '/lorebooks/new': typeof LorebooksNewRoute
  '/characters/': typeof CharactersIndexRoute
  '/chats/': typeof ChatsIndexRoute
  '/lorebooks/': typeof LorebooksIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/characters/$id_/edit': typeof CharactersIdEditRoute
  '/api/backgrounds/$id/image': typeof ApiBackgroundsIdImageRoute
  '/api/characters/$id/avatar': typeof ApiCharactersIdAvatarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/admin/users'
    | '/api/chat-generate'
    | '/characters/$id'
    | '/characters/new'
    | '/chats/$id'
    | '/chats/new'
    | '/lorebooks/$id'
    | '/lorebooks/new'
    | '/characters/'
    | '/chats/'
    | '/lorebooks/'
    | '/settings/'
    | '/api/auth/$'
    | '/characters/$id/edit'
    | '/api/backgrounds/$id/image'
    | '/api/characters/$id/avatar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/admin/users'
    | '/api/chat-generate'
    | '/characters/$id'
    | '/characters/new'
    | '/chats/$id'
    | '/chats/new'
    | '/lorebooks/$id'
    | '/lorebooks/new'
    | '/characters'
    | '/chats'
    | '/lorebooks'
    | '/settings'
    | '/api/auth/$'
    | '/characters/$id/edit'
    | '/api/backgrounds/$id/image'
    | '/api/characters/$id/avatar'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/signup'
    | '/admin/users'
    | '/api/chat-generate'
    | '/characters/$id'
    | '/characters/new'
    | '/chats/$id'
    | '/chats/new'
    | '/lorebooks/$id'
    | '/lorebooks/new'
    | '/characters/'
    | '/chats/'
    | '/lorebooks/'
    | '/settings/'
    | '/api/auth/$'
    | '/characters/$id_/edit'
    | '/api/backgrounds/$id/image'
    | '/api/characters/$id/avatar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiChatGenerateRoute: typeof ApiChatGenerateRoute
  CharactersIdRoute: typeof CharactersIdRoute
  CharactersNewRoute: typeof CharactersNewRoute
  ChatsIdRoute: typeof ChatsIdRoute
  ChatsNewRoute: typeof ChatsNewRoute
  LorebooksIdRoute: typeof LorebooksIdRoute
  LorebooksNewRoute: typeof LorebooksNewRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
  LorebooksIndexRoute: typeof LorebooksIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CharactersIdEditRoute: typeof CharactersIdEditRoute
  ApiBackgroundsIdImageRoute: typeof ApiBackgroundsIdImageRoute
  ApiCharactersIdAvatarRoute: typeof ApiCharactersIdAvatarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lorebooks/': {
      id: '/lorebooks/'
      path: '/lorebooks'
      fullPath: '/lorebooks/'
      preLoaderRoute: typeof LorebooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lorebooks/new': {
      id: '/lorebooks/new'
      path: '/lorebooks/new'
      fullPath: '/lorebooks/new'
      preLoaderRoute: typeof LorebooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lorebooks/$id': {
      id: '/lorebooks/$id'
      path: '/lorebooks/$id'
      fullPath: '/lorebooks/$id'
      preLoaderRoute: typeof LorebooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/new': {
      id: '/chats/new'
      path: '/chats/new'
      fullPath: '/chats/new'
      preLoaderRoute: typeof ChatsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$id': {
      id: '/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof ChatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/new': {
      id: '/characters/new'
      path: '/characters/new'
      fullPath: '/characters/new'
      preLoaderRoute: typeof CharactersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/characters/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-generate': {
      id: '/api/chat-generate'
      path: '/api/chat-generate'
      fullPath: '/api/chat-generate'
      preLoaderRoute: typeof ApiChatGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id_/edit': {
      id: '/characters/$id_/edit'
      path: '/characters/$id/edit'
      fullPath: '/characters/$id/edit'
      preLoaderRoute: typeof CharactersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/characters/$id/avatar': {
      id: '/api/characters/$id/avatar'
      path: '/api/characters/$id/avatar'
      fullPath: '/api/characters/$id/avatar'
      preLoaderRoute: typeof ApiCharactersIdAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backgrounds/$id/image': {
      id: '/api/backgrounds/$id/image'
      path: '/api/backgrounds/$id/image'
      fullPath: '/api/backgrounds/$id/image'
      preLoaderRoute: typeof ApiBackgroundsIdImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiChatGenerateRoute: ApiChatGenerateRoute,
  CharactersIdRoute: CharactersIdRoute,
  CharactersNewRoute: CharactersNewRoute,
  ChatsIdRoute: ChatsIdRoute,
  ChatsNewRoute: ChatsNewRoute,
  LorebooksIdRoute: LorebooksIdRoute,
  LorebooksNewRoute: LorebooksNewRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  ChatsIndexRoute: ChatsIndexRoute,
  LorebooksIndexRoute: LorebooksIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CharactersIdEditRoute: CharactersIdEditRoute,
  ApiBackgroundsIdImageRoute: ApiBackgroundsIdImageRoute,
  ApiCharactersIdAvatarRoute: ApiCharactersIdAvatarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
